export const LOCALES = [
  { id: 'zh', short: '中', name: '中文', htmlLang: 'zh-CN' },
  { id: 'en', short: 'EN', name: 'English', htmlLang: 'en' },
  { id: 'ja', short: '日', name: '日本語', htmlLang: 'ja' },
];

export function resolveLocale(saved) {
  return LOCALES.some(locale => locale.id === saved) ? saved : 'en';
}

export const UI_COPY = {
  zh: {
    skip: '跳到章节地图',
    railKicker: '读书札记 · ROSETTE 01',
    author: 'Sandrine Banas 著',
    railDescription: '把代码当成一种能留下意义的手艺。',
    progress: '阅读进度',
    readOf: '已读',
    dimensions: '美的八个维度',
    dimensionNames: ['叙事', '简单性', '意图清晰性', '表达力', '纯粹性', '可持续性', '持久性', '创造力'],
    dimensionIntro: '玫瑰花窗（rosette）不是八项独立的评分，而是一组相互增强的品质。叙事、简单性、意图清晰性、表达力、纯粹性与可持续性彼此交叠；创造力位于中心，将它们结合起来；持久性则构成共同基础。美来自针对具体问题的平衡，而不是把每一项都推到极致。',
    dimensionExample: '实践示例',
    dimensionSource: '依据第一章 1.1.1–1.1.8 节整理；以下示例为本站补充，并非原文引述。',
    language: '界面语言',
    heroKicker: 'A READER’S FIELD GUIDE / 2026',
    heroTitle: '代码也可以有\n美学。',
    heroBody: '一份关于软件手艺的阅读地图：从叙事、简单性，到纯粹、持久与创造力。把十章书，折叠成一张可以反复回来的桌面。',
    openMap: '打开章节地图',
    chapterMap: '章节地图',
    chapterIntro: '十章，十种观察代码的方式。',
    chapterCount: '10 chapters / 8 dimensions',
    searchLabel: '搜索笔记',
    searchPlaceholder: '搜索章节、关键词或概念…',
    filterLabel: '按主题筛选',
    all: '全部',
    filters: { craft: '手艺', story: '叙事', clarity: '清晰', purity: '纯粹', resilience: '韧性', sustainable: '可持续', creative: '创造力' },
    resultCount: '章匹配',
    noResultsTitle: '这张地图上暂时没有这条路。',
    noResultsBody: '试试更短的关键词，或者清除筛选，重新漫游一次。',
    resetFilters: '清除搜索与筛选',
    noteKicker: 'CURRENT NOTE / 当前札记',
    noteTitle: '把读到的，留下来。',
    noteIntro: '选一章，让它在右侧展开。这里不是摘要终点，而是下一次思考的起点。',
    keyTakeaway: '我带走的三件事',
    quoteLabel: '一句提炼',
    markRead: '标为已读',
    markUnread: '标为未读',
    selected: '当前选择',
    previous: '上一章',
    next: '下一章',
    resetProgress: '重置阅读进度',
    resetDone: '进度已清空',
    liveSelected: '已打开',
    liveRead: '阅读状态已更新',
    footer: '读书笔记站 · 为代码留下审美证据',
    notebookEmpty: '还没有匹配的章节',
  },
  en: {
    skip: 'Skip to chapter map',
    railKicker: 'READER’S NOTES · ROSETTE 01',
    author: 'by Sandrine Banas',
    railDescription: 'Treat code as a craft that can leave meaning behind.',
    progress: 'Reading progress',
    readOf: 'read',
    dimensions: 'Eight dimensions of beauty',
    dimensionNames: ['Storytelling', 'Simplicity', 'Clarity of intent', 'Expressiveness', 'Purity', 'Sustainability', 'Durability', 'Creativity'],
    dimensionIntro: 'The rosette is not eight independent scores, but a set of mutually reinforcing qualities. Storytelling, simplicity, clarity of intent, expressiveness, purity, and sustainability overlap. Creativity sits at the center, bringing them together, while durability provides their common foundation. Beauty comes from balancing them for a particular problem, not maximizing every dimension.',
    dimensionExample: 'In practice',
    dimensionSource: 'Summarized from chapter 1, sections 1.1.1–1.1.8. The examples below are editorial additions, not quotations from the book.',
    language: 'Interface language',
    heroKicker: 'A READER’S FIELD GUIDE / 2026',
    heroTitle: 'Code can have\nan aesthetic.',
    heroBody: 'A reading map for software craft — from storytelling and simplicity to purity, durability, and creativity. Ten chapters, folded into a desk you can return to.',
    openMap: 'Open the chapter map',
    chapterMap: 'Chapter map',
    chapterIntro: 'Ten chapters. Ten ways to look at code.',
    chapterCount: '10 chapters / 8 dimensions',
    searchLabel: 'Search notes',
    searchPlaceholder: 'Search chapters, keywords, or ideas…',
    filterLabel: 'Filter by theme',
    all: 'All',
    filters: { craft: 'Craft', story: 'Story', clarity: 'Clarity', purity: 'Purity', resilience: 'Resilience', sustainable: 'Sustainable', creative: 'Creative' },
    resultCount: 'chapters match',
    noResultsTitle: 'There is no path here yet.',
    noResultsBody: 'Try a shorter phrase, or clear the filters and wander the map again.',
    resetFilters: 'Clear search & filters',
    noteKicker: 'CURRENT NOTE / FIELD LOG',
    noteTitle: 'Keep what you read.',
    noteIntro: 'Choose a chapter to open it on the right. This is not the end of the summary; it is the start of the next thought.',
    keyTakeaway: 'Three things I’m keeping',
    quoteLabel: 'One line to keep',
    markRead: 'Mark as read',
    markUnread: 'Mark as unread',
    selected: 'Selected',
    previous: 'Previous',
    next: 'Next',
    resetProgress: 'Reset reading progress',
    resetDone: 'Progress cleared',
    liveSelected: 'Opened',
    liveRead: 'Reading status updated',
    footer: 'Reader’s notes · leaving aesthetic evidence for code',
    notebookEmpty: 'No matching chapter',
  },
  ja: {
    skip: '章の地図へ移動',
    railKicker: '読書ノート · ROSETTE 01',
    author: 'Sandrine Banas 著',
    railDescription: 'コードを、意味を残せる手仕事として捉える。',
    progress: '読書の進み具合',
    readOf: '既読',
    dimensions: '美しさの八つの軸',
    dimensionNames: ['物語', 'シンプルさ', '意図の明快さ', '表現力', '純粋さ', '持続可能性', '耐久性', '創造性'],
    dimensionIntro: 'ロゼットは八つの独立した点数ではなく、互いを強め合う性質の組み合わせだ。物語、シンプルさ、意図の明快さ、表現力、純粋さ、持続可能性が重なり合い、中心の創造性がそれらを結び、耐久性が共通の土台になる。すべてを極限まで高めるのではなく、目の前の問題に応じたバランスが美しさを生む。',
    dimensionExample: '実践例',
    dimensionSource: '第1章の1.1.1〜1.1.8節をもとに整理。以下の例は本サイトによる補足であり、原文の引用ではありません。',
    language: '表示言語',
    heroKicker: 'A READER’S FIELD GUIDE / 2026',
    heroTitle: 'コードにも、\n美学がある。',
    heroBody: '物語とシンプルさから、純粋さ、耐久性、創造性まで。ソフトウェアの手仕事を読むための地図を、何度でも戻れる机のようにまとめた。',
    openMap: '章の地図をひらく',
    chapterMap: '章の地図',
    chapterIntro: '10章、コードを見る10の視点。',
    chapterCount: '10 chapters / 8 dimensions',
    searchLabel: 'ノートを検索',
    searchPlaceholder: '章・キーワード・考えを検索…',
    filterLabel: 'テーマで絞り込む',
    all: 'すべて',
    filters: { craft: '手仕事', story: '物語', clarity: '明晰さ', purity: '純粋さ', resilience: 'しなやかさ', sustainable: '持続可能性', creative: '創造性' },
    resultCount: '章が一致',
    noResultsTitle: 'この地図にはまだ道がありません。',
    noResultsBody: '短い言葉を試すか、絞り込みを解除してもう一度歩いてみてください。',
    resetFilters: '検索と絞り込みを解除',
    noteKicker: 'CURRENT NOTE / 現在のノート',
    noteTitle: '読んだものを、残す。',
    noteIntro: '章を選ぶと右側に開きます。要約の終点ではなく、次の思考の出発点です。',
    keyTakeaway: '持ち帰る三つのこと',
    quoteLabel: '残したい一行',
    markRead: '既読にする',
    markUnread: '未読に戻す',
    selected: '選択中',
    previous: '前の章',
    next: '次の章',
    resetProgress: '読書の進み具合をリセット',
    resetDone: '進み具合を消去しました',
    liveSelected: '開きました',
    liveRead: '読書状態を更新しました',
    footer: '読書ノート · コードに美学の証拠を残す',
    notebookEmpty: '一致する章がありません',
  },
};

export const FILTERS = ['all', 'craft', 'story', 'clarity', 'purity', 'resilience', 'sustainable', 'creative'];

export const DIMENSIONS = [
  { id: 'storytelling', tone: 'coral',
    description: {
      zh: '让代码像连贯的故事一样展开，使读者能顺着命名、动作和层次理解业务逻辑。它不只是容易读，更要让逻辑容易跟随和记住。',
      en: 'Let code unfold as a coherent story. Names, actions, and levels of abstraction help readers follow and remember the business logic, rather than merely decipher instructions.',
      ja: 'コードを一貫した物語として展開する。名前、動作、抽象度の階層を通して、業務の流れを追いやすく、記憶に残りやすくする。',
    },
    example: {
      zh: '让下单流程依次读作“校验订单 → 计算金额 → 保存订单”，再把细节放进各自的方法。',
      en: 'Make an order workflow read “validate order → calculate total → save order,” with the details inside those methods.',
      ja: '注文処理を「注文の検証 → 合計の計算 → 注文の保存」と読めるようにし、詳細は各メソッドに置く。',
    },
  },
  { id: 'simplicity', tone: 'gold',
    description: {
      zh: '不是消灭所有复杂性，也不是一味减少行数，而是把必要的复杂提炼成清晰、可理解、可维护的形式，并持续抑制不必要的增长。',
      en: 'Simplicity is not removing all complexity or minimizing line count. It means refining necessary complexity into an understandable, maintainable form and keeping unnecessary growth under control.',
      ja: '複雑さをすべてなくすことでも、行数だけを減らすことでもない。必要な複雑さを理解・保守しやすい形に整え、不要な増大を抑え続ける。',
    },
    example: {
      zh: '把多层嵌套条件整理为清楚的提前返回，让主要处理路径一眼可见。',
      en: 'Replace deeply nested conditions with clear early returns so the main path remains easy to see.',
      ja: '深く入れ子になった条件を明快な早期リターンに整理し、主要な処理の流れを見えやすくする。',
    },
  },
  { id: 'intent', tone: 'teal',
    description: {
      zh: '让代码直接表达“要做什么”。通过显式的数据建模、准确的命名，以及围绕数据结构组织的行为，减少读者猜测目的的负担。',
      en: 'Communicate what the code is trying to do. Explicit data models, precise names, and behavior organized around those structures reduce the need to guess its purpose.',
      ja: 'コードが「何をしたいのか」を直接伝える。明示的なデータモデル、正確な名前、その構造に沿った振る舞いで、目的を推測する負担を減らす。',
    },
    example: {
      zh: '用包含金额和币种的 Money 类型表达价格，而不是让一个含义不明的数字在系统里传递。',
      en: 'Represent a price with a Money type containing an amount and currency, rather than passing an unexplained number around.',
      ja: '価格を意味の曖昧な数値で渡すのではなく、金額と通貨を持つ Money 型で表す。',
    },
  },
  { id: 'expressiveness', tone: 'blue',
    description: {
      zh: '善用语言本身的能力，把想法写成清楚、简练、自然的表达。简洁应帮助理解；如果语法技巧遮住了逻辑，就越过了边界。',
      en: 'Use the language’s strengths to express ideas clearly, concisely, and naturally. Brevity should aid understanding; clever syntax that hides the logic has crossed the line.',
      ja: '言語の力を生かし、考えを明快で簡潔かつ自然に表す。短さは理解を助けるためのもの。巧妙な構文が論理を隠すなら、やり過ぎだ。',
    },
    example: {
      zh: '用清晰命名的筛选条件和映射步骤表达集合转换，避免堆成难懂的一行。',
      en: 'Express a collection transformation with clearly named filtering and mapping steps, without compressing it into an opaque one-liner.',
      ja: 'コレクションの変換を、名前の明快な絞り込みと変換の手順で表し、読みにくい一行へ無理に詰め込まない。',
    },
  },
  { id: 'purity', tone: 'coral',
    description: {
      zh: '让行为可预测、无隐藏副作用：相同输入得到相同输出，不悄悄改变外部状态。纯粹性有助于测试、理解与复用，但不是函数式编程独有的品质。',
      en: 'Keep behavior predictable and free of hidden side effects: the same inputs produce the same outputs without silently changing external state. Purity supports testing, comprehension, and reuse; it is not exclusive to functional programming.',
      ja: '同じ入力から同じ出力を返し、外部状態をひそかに変えない、予測可能な振る舞いを目指す。テスト、理解、再利用を助ける性質であり、関数型プログラミングだけのものではない。',
    },
    example: {
      zh: '让折扣计算只接收价格和折扣规则并返回结果，把数据库写入留给独立的步骤。',
      en: 'Let a discount calculation accept a price and discount rules and return a result; keep database writes in a separate step.',
      ja: '割引計算は価格と割引ルールを受け取って結果を返すだけにし、データベースへの書き込みは別の手順に分ける。',
    },
  },
  { id: 'sustainability', tone: 'teal',
    description: {
      zh: '把对逻辑的节制也用于计算、内存、存储、网络和硬件，避免不必要的资源消耗，同时考虑运行成本与环境影响。',
      en: 'Apply the same discipline to computation, memory, storage, networks, and hardware that good code applies to logic. Avoid unnecessary resource use, considering both operating cost and environmental impact.',
      ja: '論理を整えるのと同じ節度を、計算、メモリ、ストレージ、通信、ハードウェアにも適用する。運用コストと環境への影響を考え、不要な資源消費を避ける。',
    },
    example: {
      zh: '只查询和传输当前页面需要的字段，避免每次请求都读取整个数据集。',
      en: 'Query and transfer only the fields a page needs, rather than reading the whole dataset for every request.',
      ja: '毎回データ全体を読むのではなく、その画面に必要な項目だけを取得・転送する。',
    },
  },
  { id: 'durability', tone: 'gold',
    description: {
      zh: '让设计经得起时间和需求变化，在演进时仍保持可用、可理解的结构。它不是预测所有未来需求，而是为变化留下合理的弹性。',
      en: 'Build designs that remain useful and understandable as time passes and demands change. Durability is not predicting every future requirement; it is providing enough structure and flexibility to evolve.',
      ja: '時間や要求の変化に耐え、進化しても使え、理解できる構造を保つ。将来の要求をすべて予測するのではなく、変化に対応する適切な柔軟性を持たせる。',
    },
    example: {
      zh: '把外部支付服务放在清楚的接口之后，更换供应商时不必改写核心业务规则。',
      en: 'Put an external payment service behind a clear interface so changing providers does not require rewriting core business rules.',
      ja: '外部の決済サービスを明快なインターフェースの背後に置き、提供元の変更で中核の業務ルールを書き直さずに済むようにする。',
    },
  },
  { id: 'creativity', tone: 'blue',
    description: {
      zh: '把原则转化为可工作的解法。在可读性、性能、期限或遗留系统等约束中，运用知识、直觉、专注与耐心，重新组合手中的工具。',
      en: 'Turn principles into working solutions. Within constraints such as readability, performance, deadlines, or legacy systems, combine the tools at hand using knowledge, intuition, focus, and persistence.',
      ja: '原則を実際に動く解法へ変える力。可読性、性能、納期、既存システムなどの制約の中で、知識、直感、集中力、粘り強さを使い、手元の道具を組み合わせ直す。',
    },
    example: {
      zh: '面对慢报表，先重新审视计算时机和数据组织，再决定是否需要重写整个系统。',
      en: 'For a slow report, reconsider when calculations happen and how data is organized before deciding to rewrite the whole system.',
      ja: '遅いレポートに対して、システム全体の書き直しを決める前に、計算のタイミングやデータのまとめ方を見直す。',
    },
  },
];

export const CHAPTERS = [
  {
    id: 'aesthetics', number: 1, theme: 'craft', accent: 'coral', illustration: 'rosette',
    title: { zh: '代码的美学', en: 'The aesthetics of code', ja: 'コードの美学' },
    eyebrow: { zh: 'ROSETTE / 美的起点', en: 'ROSETTE / THE STARTING POINT', ja: 'ROSETTE / 美しさの起点' },
    summary: {
      zh: '美不是装饰，而是让代码更容易理解、维护和延展的智性秩序。',
      en: 'Beauty is not decoration; it is the intellectual order that makes code easier to understand, maintain, and extend.',
      ja: '美しさは装飾ではない。コードを理解し、保守し、拡張しやすくする知的な秩序だ。',
    },
    takeaway: {
      zh: ['用 rosette 看见八个维度如何互相增强。', '让 Optional 之类的结构把意图从防御性噪音里解放出来。', '把创造力放在中心，把持久性作为共同地基。'],
      en: ['Use the rosette to see how eight dimensions reinforce one another.', 'Let structures such as Optional free intent from defensive noise.', 'Put creativity at the center and durability underneath everything.'],
      ja: ['ロゼットで、八つの軸が互いを強める関係を見る。', 'Optional のような構造で、意図を防御的なノイズから解放する。', '創造性を中心に、耐久性を共通の土台に置く。'],
    },
    quote: { zh: '好的代码，让意义先于机制抵达读者。', en: 'In beautiful code, meaning arrives before mechanics.', ja: '美しいコードでは、仕組みより先に意味が届く。' },
    note: { zh: '第一章把“写得漂亮”从主观品味拉回到工程判断：可读、可改、可留存，都是美的一部分。', en: 'This chapter pulls “beautiful” back from personal taste into engineering judgment: readable, changeable, and lasting are all part of the aesthetic.', ja: 'この章は「美しい」を個人の好みから工学的な判断へ戻す。読みやすさ、変えやすさ、残り続けることも美の一部だ。' },
  },
  {
    id: 'narrative', number: 2, theme: 'story', accent: 'teal', illustration: 'narrative',
    title: { zh: '叙事代码', en: 'Narrative code', ja: '物語としてのコード' },
    eyebrow: { zh: 'STORY / 代码的情节', en: 'STORY / THE PLOT OF CODE', ja: 'STORY / コードの筋書き' },
    summary: {
      zh: '把业务逻辑当作故事来组织：有角色、有情节、有抵达终点的动作。',
      en: 'Organize business logic as a story: with characters, a plot, and actions that reach a meaningful ending.',
      ja: 'ビジネスロジックを物語として組み立てる。登場人物、筋書き、意味のある結末を持たせる。',
    },
    takeaway: {
      zh: ['先辨认代码在讲哪种故事：递送、清理、防御、归档或转换。', '让方法像动作、场景、章节和目录一样分层。', '高层方法应该像目录，让读者先抓住全局再下潜。'],
      en: ['Name the plot: delivering, cleaning, defense, archiving, or transformation.', 'Layer methods like actions, scenes, chapters, and a table of contents.', 'A high-level method should work like a table of contents before readers dive in.'],
      ja: ['物語の型を見つける。届ける、掃除する、守る、保管する、変換する。', 'メソッドをアクション、場面、章、目次のように階層化する。', '高レベルのメソッドは目次のように、全体像を先に渡す。'],
    },
    quote: { zh: '先让读者知道发生了什么，再让他看见它如何发生。', en: 'Let the reader know what happens before showing how it happens.', ja: 'まず何が起きるかを伝え、その後でどう起きるかを見せる。' },
    note: { zh: '叙事不是把变量取成文学化的名字，而是让抽象层级保持一致，让每一段代码都承担故事中的一个动作。', en: 'Narrative is not about literary variable names. It is about keeping abstraction levels consistent, so each piece of code carries one action in the story.', ja: '物語とは文学的な変数名ではない。抽象度を揃え、コードの各部分に物語の一つの動作を担わせることだ。' },
  },
  {
    id: 'simplicity', number: 3, theme: 'clarity', accent: 'gold', illustration: 'simplicity',
    title: { zh: '简单性的复杂艺术', en: 'The complex art of simplicity', ja: 'シンプルさという複雑な技術' },
    eyebrow: { zh: 'SIMPLICITY / 逆熵练习', en: 'SIMPLICITY / ANTI-ENTROPY', ja: 'SIMPLICITY / 逆エントロピー' },
    summary: {
      zh: '复杂度会自然增长；简单性是一种持续注入能量、把复杂提炼成清晰形状的纪律。',
      en: 'Complexity grows by default; simplicity is the discipline of injecting steady energy to refine it into a clear shape.',
      ja: '複雑さは放っておくと増える。シンプルさとは、複雑さを明快な形へ磨くために力を注ぎ続ける規律だ。',
    },
    takeaway: {
      zh: ['先识别认知复杂度，而不是只盯着行数。', 'Prevent、Organize、Reduce、Hide、Investigate、Endure 是六个动手杠杆。', '简单不是删掉所有东西，而是给必要的复杂找到清楚的位置。'],
      en: ['Look for cognitive complexity, not only line count.', 'Prevent, Organize, Reduce, Hide, Investigate, and Endure are six practical levers.', 'Simplicity does not delete every complexity; it gives necessary complexity a clear place.'],
      ja: ['行数だけでなく、認知的な複雑さを見る。', 'Prevent、Organize、Reduce、Hide、Investigate、Endure の六つのレバーを使う。', 'シンプルさはすべてを削ることではなく、必要な複雑さに居場所を与えること。'],
    },
    quote: { zh: '简单不是更少，而是更清楚。', en: 'Simple is not less; it is clearer.', ja: 'シンプルとは少ないことではなく、明快なことだ。' },
    note: { zh: '我喜欢这里的“逆熵”视角：代码不会自动变好，简单性是需要被反复维护的状态。', en: 'I like the anti-entropy lens: code does not become better on its own. Simplicity is a state that must be maintained.', ja: '「逆エントロピー」という視点が印象に残る。コードは自然には良くならず、シンプルさは守り続ける状態なのだ。' },
  },
  {
    id: 'intent', number: 4, theme: 'clarity', accent: 'blue', illustration: 'intent',
    title: { zh: '用优雅的数据建模表达意图', en: 'Expressing clarity of intent through elegant data modeling', ja: '優雅なデータモデリングで意図を明快にする' },
    eyebrow: { zh: 'INTENT / 让数据说话', en: 'INTENT / LET DATA SPEAK', ja: 'INTENT / データに語らせる' },
    summary: {
      zh: '当数据被显式建模，行为就能围绕它自然组织，代码的目的无需额外解释。',
      en: 'When data is modeled explicitly, behavior can organize itself around it and the code needs less explanation.',
      ja: 'データを明示的にモデル化すると、振る舞いがその周りに自然に整い、コードの目的を説明しすぎずに済む。',
    },
    takeaway: {
      zh: ['小型数据载体能降低可变状态和封装负担。', '记录、模式匹配和代数数据类型，让域模型更接近问题本身。', '好的数据结构不是被动容器，而是意图的可读接口。'],
      en: ['Small data carriers reduce mutable state and the burden of encapsulation.', 'Records, pattern matching, and algebraic data types keep the domain close to the problem.', 'A good data structure is not passive storage; it is a readable interface for intent.'],
      ja: ['小さなデータキャリアは可変状態とカプセル化の負担を減らす。', 'レコードやパターンマッチ、代数的データ型でドメインを問題に近づける。', '良いデータ構造は受け皿ではなく、意図を読めるインターフェースだ。'],
    },
    quote: { zh: '让数据的形状，提前回答“这是什么”。', en: 'Let the shape of the data answer “what is this?” early.', ja: 'データの形に「これは何か」を先に答えさせる。' },
    note: { zh: '这一章让我重新看待 record：它不是少写几行样板，而是把领域中的小事实摆到台面上。', en: 'This chapter made me see records differently: they are not just less boilerplate, but small domain facts placed in plain sight.', ja: 'record を、単に定型コードを減らす機能ではなく、ドメインの小さな事実を表に出すものとして読み直した。' },
  },
  {
    id: 'expressiveness', number: 5, theme: 'craft', accent: 'coral', illustration: 'expressiveness',
    title: { zh: '表达力', en: 'Expressiveness', ja: '表現力' },
    eyebrow: { zh: 'LANGUAGE / 借用语言的力量', en: 'LANGUAGE / USE THE GRAIN', ja: 'LANGUAGE / 言語の力を借りる' },
    summary: {
      zh: '用语言真正提供的表达能力把想法翻译成短而清晰的代码，但不要把简洁推到晦涩。',
      en: 'Use the language’s real expressive power to translate ideas into concise, clear code — without crossing into obscurity.',
      ja: '言語が本来持つ表現力で考えを短く明快なコードへ翻訳する。ただし簡潔さを難解さへ押し進めない。',
    },
    takeaway: {
      zh: ['语言升级的价值，在于让意图变得可见。', '把 switch、when、sealed hierarchy 等工具和领域模型一起考虑。', '每一次压缩都要问：读者是否仍能顺着逻辑走完？'],
      en: ['The value of language evolution is making intent more visible.', 'Consider switch, when, sealed hierarchies, and the domain model together.', 'With every compression, ask whether a reader can still follow the logic.'],
      ja: ['言語の進化の価値は、意図を見えるようにすること。', 'switch、when、sealed hierarchy とドメインモデルを一緒に考える。', '短くするたびに、読み手が論理を追えるか問い直す。'],
    },
    quote: { zh: '表达力的边界，是读者还能不能继续呼吸。', en: 'The boundary of expressiveness is whether the reader can still breathe.', ja: '表現力の境界は、読み手がまだ息をできるかどうかだ。' },
    note: { zh: '真正的精炼不是炫技，而是让语言的形状和问题的形状重叠。', en: 'Real concision is not showing off; it is making the shape of the language overlap with the shape of the problem.', ja: '本当の簡潔さは技巧の披露ではない。言語の形と問題の形を重ねることだ。' },
  },
  {
    id: 'purity', number: 6, theme: 'purity', accent: 'teal', illustration: 'purity',
    title: { zh: '拥抱纯粹：函数式编程', en: 'Embracing purity with functional programming', ja: '関数型プログラミングで純粋さを抱く' },
    eyebrow: { zh: 'PURITY / 输入 → 输出', en: 'PURITY / INPUT → OUTPUT', ja: 'PURITY / 入力 → 出力' },
    summary: {
      zh: '纯粹性让行为可预测、无隐藏副作用；函数式编程把这种数学般的美带进日常代码。',
      en: 'Purity makes behavior predictable and free of hidden side effects; functional programming brings mathematical beauty into daily code.',
      ja: '純粋さは振る舞いを予測可能にし、隠れた副作用を減らす。関数型プログラミングは数学的な美を日常のコードへ運ぶ。',
    },
    takeaway: {
      zh: ['纯函数把测试、阅读和复用变得轻盈。', '组合与 pipeline 能把复杂处理拆成可观察的步骤。', '声明式不是越长越好；丑陋的 pipeline 同样会隐藏意图。'],
      en: ['Pure functions make testing, reading, and reuse lighter.', 'Composition and pipelines turn complex processing into observable steps.', 'Declarative does not mean longer is better; ugly pipelines can hide intent too.'],
      ja: ['純粋関数はテスト、読解、再利用を軽くする。', '合成とパイプラインで、複雑な処理を観察できる段階へ分ける。', '宣言的だから良いわけではない。醜いパイプラインも意図を隠す。'],
    },
    quote: { zh: '输入进来，输出出去，惊喜留在别的地方。', en: 'Let input go in and output come out; keep surprises somewhere else.', ja: '入力を入れ、出力を出す。驚きは別の場所に置いておく。' },
    note: { zh: '我把纯粹理解成一种“可预测的礼貌”：函数不偷偷改动世界，读者就敢于组合它。', en: 'I read purity as predictable courtesy: when a function does not secretly change the world, readers dare to compose it.', ja: '純粋さを「予測できる礼儀」として読んだ。関数が世界をこっそり変えなければ、読み手は安心して組み合わせられる。' },
  },
  {
    id: 'failure', number: 7, theme: 'resilience', accent: 'gold', illustration: 'failure',
    title: { zh: '优雅地处理失败', en: 'Handling failure with grace', ja: '失敗をしなやかに扱う' },
    eyebrow: { zh: 'FAILURE / 失败的礼仪', en: 'FAILURE / THE ETIQUETTE OF FAILURE', ja: 'FAILURE / 失敗の作法' },
    summary: {
      zh: '先区分业务错误、技术问题、编程错误与致命错误，再决定谁来处理、如何记录、何时退出。',
      en: 'First distinguish business errors, technical problems, programming errors, and fatal errors — then decide who handles, logs, or exits.',
      ja: '業務エラー、技術的な問題、プログラミングエラー、致命的エラーを分け、誰が扱い、記録し、いつ終了するかを決める。',
    },
    takeaway: {
      zh: ['入口防御、清晰的错误边界和 fallback 是同一套设计。', 'lazy catch、重复日志和无意义消息会让故障更难诊断。', '优雅不是吞掉错误，而是给错误一个可行动的去处。'],
      en: ['Defending entry points, clear error boundaries, and fallbacks are one design system.', 'Lazy catches, duplicate logs, and useless messages make incidents harder to diagnose.', 'Grace is not swallowing errors; it gives each error an actionable place to go.'],
      ja: ['入口の防御、明確なエラー境界、フォールバックは一つの設計体系だ。', '雑な catch、重複ログ、役に立たないメッセージは診断を難しくする。', 'しなやかさとはエラーを隠すことではなく、行動につながる居場所を与えること。'],
    },
    quote: { zh: '错误处理的质量，取决于失败之后还剩多少方向感。', en: 'Good failure handling leaves a sense of direction after things break.', ja: '良い失敗処理は、壊れた後にも進む方向を残す。' },
    note: { zh: '“不要什么都 catch”很容易说，但真正困难的是把每类失败都放到最懂它的边界上。', en: '“Do not catch everything” is easy to say. The hard part is giving each kind of failure to the boundary that understands it best.', ja: '「何でも catch しない」は言いやすい。本当に難しいのは、失敗の種類ごとに最も理解できる境界へ渡すことだ。' },
  },
  {
    id: 'sustainability', number: 8, theme: 'sustainable', accent: 'teal', illustration: 'sustainability',
    title: { zh: '可持续性', en: 'Sustainability', ja: '持続可能性' },
    eyebrow: { zh: 'PLANET / 软件的隐形成本', en: 'PLANET / THE HIDDEN COST', ja: 'PLANET / 見えないコスト' },
    summary: {
      zh: '软件不只消耗算力，也参与设备制造、能源与淘汰的完整生命周期；绿色设计要从细节开始。',
      en: 'Software consumes more than compute: it participates in the full lifecycle of devices, energy, and obsolescence. Green design starts with details.',
      ja: 'ソフトウェアが消費するのは計算資源だけではない。デバイス、エネルギー、廃棄までのライフサイクルに関わる。',
    },
    takeaway: {
      zh: ['延长设备寿命，往往比一次性优化更有效。', '节制的包、存储、通信、执行与内存，是可实践的 green patterns。', '碳感知设计把运行地点与时间也纳入工程决策。'],
      en: ['Extending device life can matter more than a one-off optimization.', 'Lean packaging, storage, communication, execution, and memory are practical green patterns.', 'Carbon-aware design includes where and when software runs in engineering decisions.'],
      ja: ['デバイスの寿命を延ばすことは、一度きりの最適化より効くことがある。', '軽いパッケージ、保存、通信、実行、メモリは実践的なグリーンパターンだ。', 'カーボンアウェア設計では、どこでいつ動かすかも技術判断に含める。'],
    },
    quote: { zh: '少用一点资源，也是在为未来保留一点选择。', en: 'Using a little less resource leaves a little more choice for the future.', ja: '資源を少し節約することは、未来の選択肢を少し残すことだ。' },
    note: { zh: '这一章把“性能”扩展成了更长的时间尺度：不仅系统要活得久，承载它的设备和环境也要。', en: 'This chapter stretches “performance” across a longer timeline: not only should systems last, but the devices and environments carrying them should too.', ja: 'この章は「性能」を長い時間軸へ広げる。システムだけでなく、それを支えるデバイスと環境も長く保つべきなのだ。' },
  },
  {
    id: 'durability', number: 9, theme: 'resilience', accent: 'blue', illustration: 'durability',
    title: { zh: '软件设计中的持久性', en: 'Durability in software design', ja: 'ソフトウェア設計の耐久性' },
    eyebrow: { zh: 'TIME / 经得起变化', en: 'TIME / BUILT FOR CHANGE', ja: 'TIME / 変化に耐える' },
    summary: {
      zh: '用关注点分离、松耦合高内聚、韧性、测试与稳定契约，让软件能工作、能变化、也能被信任。',
      en: 'Separation of concerns, loose coupling, resilience, tests, and stable contracts help software work now, adapt later, and stay trusted.',
      ja: '関心の分離、疎結合、高凝集、レジリエンス、テスト、安定した契約が、変化に耐え信頼されるソフトウェアを作る。',
    },
    takeaway: {
      zh: ['从 spaghetti 到 lasagna，再到 ravioli，架构一直在寻找更清晰的边界。', '高内聚、低耦合不是口号，而是每一层都要做的局部判断。', '测试包围实现，稳定的公共接口则保护外部信任。'],
      en: ['From spaghetti to lasagna to ravioli, architecture keeps searching for clearer boundaries.', 'High cohesion and low coupling are local decisions at every level, not slogans.', 'Tests surround implementation, while stable public interfaces protect trust outside the system.'],
      ja: ['スパゲッティ、ラザニア、ラビオリへ。アーキテクチャはより明快な境界を探し続ける。', '高凝集・疎結合はスローガンではなく、各レベルでの局所的な判断だ。', 'テストが実装を囲み、安定した公開インターフェースが外部の信頼を守る。'],
    },
    quote: { zh: '持久性不是不变，而是变化发生时仍然站得住。', en: 'Durability is not staying unchanged; it is standing when change arrives.', ja: '耐久性とは変わらないことではなく、変化が来ても立ち続けることだ。' },
    note: { zh: '这章像 rosette 的地基：前面所有审美判断，最后都要回答一个时间问题——几年后还读得懂吗？', en: 'This chapter feels like the rosette’s foundation: every aesthetic choice eventually faces a time question — will it still be readable years from now?', ja: 'この章はロゼットの土台のようだ。すべての美的判断は最後に時間へ問われる――数年後も読めるか。' },
  },
  {
    id: 'creativity', number: 10, theme: 'creative', accent: 'coral', illustration: 'creativity',
    title: { zh: '代码与问题解决中的创造力', en: 'Creativity in code and problem-solving', ja: 'コードと問題解決の創造性' },
    eyebrow: { zh: 'CREATE / 约束中的自由', en: 'CREATE / FREEDOM IN CONSTRAINTS', ja: 'CREATE / 制約の中の自由' },
    summary: {
      zh: '创造力不是凭空闪现，而是知识、技能、耐心与限制相遇后，对问题重新命名和重组。',
      en: 'Creativity is not a lightning strike; it is knowledge, skill, patience, and constraints meeting to rename and rearrange a problem.',
      ja: '創造性は突然のひらめきではない。知識、技術、忍耐、制約が出会い、問題を捉え直し組み替えることだ。',
    },
    takeaway: {
      zh: ['适度的约束会缩小搜索空间，也为新解法腾出注意力。', '把问题解决拆成理解、澄清、调查、孵化、评估与反思。', 'AI 可以处理惯例，但判断、取舍和创造性预见仍属于人的手艺。'],
      en: ['The right constraints narrow the search space and free attention for new solutions.', 'Break problem-solving into knowledge, clarification, investigation, incubation, evaluation, and reflection.', 'AI can handle convention; judgment, trade-offs, and creative foresight remain human craft.'],
      ja: ['適切な制約は探索範囲を絞り、新しい解決に注意を向けさせる。', '問題解決を知識、明確化、調査、熟成、評価、振り返りに分ける。', 'AI は定型を扱えても、判断や選択、創造的な先読みは人の手仕事として残る。'],
    },
    quote: { zh: '限制不是创意的墙，有时是它的取景框。', en: 'A constraint is not always a wall; sometimes it is a frame for the idea.', ja: '制約はいつも壁ではない。ときにはアイデアのためのフレームになる。' },
    note: { zh: '最后一章没有把创造力神秘化，而是给它安排了流程：先积累，再澄清，在循环里让好想法浮上来。', en: 'The final chapter does not mystify creativity. It gives it a process: gather, clarify, and let the good idea surface through a loop.', ja: '最後の章は創造性を神秘化しない。蓄え、明確にし、ループの中で良いアイデアを浮かび上がらせる手順を与える。' },
  },
];
