export const SITE_COPY = {
  zh: {
    coverArtwork: '抽象墨线莫比乌斯绸带，在留白中缓缓扭转与舒展。',
    notes: '读书札记', gallery: '章节画廊', about: '关于本书', start: '从第一章开始',
    kicker: '关于代码，也关于创造。', subtitle: '在逻辑的秩序里，\n看见美的可能。',
    introduction: '循着 Sandrine Banas 的十章文字，重新思考我们如何写代码。一次关于清晰、纯粹与创造力的缓慢阅读。',
    collection: '十章文字，十种形态。', collectionIntro: '每一个想法，都有自己的形状。选择一章，进入文字与图像之间。',
    chapter: '第', chapterUnit: '章', back: '返回画廊', reflection: '阅读随想', distilled: '札记提炼 · 非原文引述',
    pause: '暂停动效', play: '播放动效', read: '已读', unread: '未读', artwork: '章节插画', artworkNote: '让目光停留片刻，再回到文字。',
    aboutTitle: '好代码，值得慢慢读。',
    aboutBody: '《The Art of Code》将软件设计看作一门创造性的手艺。从叙事与数据建模，到错误处理与可持续性，Sandrine Banas 为代码之美提供了可讨论、可实践的语言。',
    aboutNotes: '本站根据提供的十章内容整理独立读书笔记。章节概要、阅读随想与一句提炼均为编辑整理；书籍内容与观点归原作者所有。',
    ending: '阅读之后，回到创造。', top: '回到顶部', edition: '三语读本 / 十章札记',
    forms: ['无尽的褶面', '故事的流向', '复杂归于清晰', '意图的形状', '语言的共振', '纯粹的回响', '绕行与重逢', '生长的规律', '时间的沉积', '约束中的绽放'],
    formNotes: ['细密的线条在扭转中汇成连续的曲面。没有起点，也没有终点，秩序与变化在同一条绸带上相遇。', '平行的叙事线保持连续，在起伏中共同抵达终点。', '左侧的纠缠渐渐舒展，必要的复杂被安置在清楚的位置。', '边界和关系构成一个可读的体积，让抽象意图拥有形状。', '两组简单的圆相遇，形成超出单个元素的表达。', '同心的波纹遵循同一规则，变化没有隐藏的惊喜。', '线条在缺口前分流，再重新汇合，失败仍然有路可走。', '种子按稳定的角度排列，有限空间里长出持续的秩序。', '层层轮廓积累成地形，结构在时间中保持可辨认。', '一条受约束的曲线反复变奏，生长出意料之外的花。'],
  },
  en: {
    coverArtwork: 'An abstract Möbius ribbon of fine ink threads, slowly twisting and unfolding in open space.',
    notes: 'Reading notes', gallery: 'The chapters', about: 'About the book', start: 'Begin with chapter one',
    kicker: 'On code. On the act of creating.', subtitle: 'Finding beauty\nin the order of logic.',
    introduction: 'A slow reading of Sandrine Banas’s ten chapters. An invitation to reconsider how we write code, through clarity, purity, and creativity.',
    collection: 'Ten chapters. Ten forms.', collectionIntro: 'Every idea has a shape of its own. Step into the space between words and images.',
    chapter: 'Chapter', chapterUnit: '', back: 'Back to the chapters', reflection: 'A reader’s reflection', distilled: 'An editorial distillation · not a book quotation',
    pause: 'Pause motion', play: 'Play motion', read: 'Read', unread: 'Unread', artwork: 'Chapter artwork', artworkNote: 'Stay with the image. Then return to the words.',
    aboutTitle: 'Good code rewards a slower reading.',
    aboutBody: 'The Art of Code considers software design a creative craft. From storytelling and data modeling to failure handling and sustainability, Sandrine Banas gives us a language to discuss and practice beauty in code.',
    aboutNotes: 'Independent reading notes based on the ten supplied chapters. Summaries, reflections, and distilled lines are editorial interpretations. The book’s content and ideas belong to its author.',
    ending: 'After reading, return to creating.', top: 'Back to top', edition: 'A trilingual edition / Ten reading notes',
    forms: ['An endless fold', 'A story in flow', 'Complexity, resolved', 'The shape of intent', 'Language in resonance', 'A pure echo', 'Diverge and return', 'The pattern of growth', 'Sediments of time', 'A bloom within bounds'],
    formNotes: ['Fine threads become a continuous surface through a twist. Without a beginning or an end, order and change meet along the same ribbon.', 'Parallel threads remain continuous, carrying a story through its turns to an ending.', 'Tangled lines open into clarity, giving necessary complexity a legible place.', 'Boundaries and relationships form a readable volume, giving abstract intent a shape.', 'Two simple families of circles meet, expressing more than either could alone.', 'Concentric ripples follow one rule; change carries no hidden surprises.', 'Lines part around a void and meet again. Failure still leaves a way forward.', 'Seeds follow a constant angle, finding enduring order within limited space.', 'Layered contours form a landscape, keeping a recognizable structure through time.', 'A constrained curve repeats with variation, growing into an unexpected flower.'],
  },
  ja: {
    coverArtwork: '余白の中でゆっくりとねじれ、ほどける、細い墨線の抽象的なメビウスの帯。',
    notes: '読書ノート', gallery: '章のギャラリー', about: '本について', start: '第一章から読む',
    kicker: 'コードと、創るということ。', subtitle: '論理の秩序に、\n美しさを見つける。',
    introduction: 'Sandrine Banas の十章を、ゆっくりと読み解く。明晰さ、純粋さ、創造性を通じて、コードの書き方を見つめ直す。',
    collection: '十の章、十のかたち。', collectionIntro: 'それぞれの考えには、固有のかたちがある。章を選び、言葉と絵のあいだへ。',
    chapter: '第', chapterUnit: '章', back: 'ギャラリーに戻る', reflection: '読んで考えたこと', distilled: 'ノートの要約 · 原文の引用ではありません',
    pause: '動きを止める', play: '動きを再生', read: '既読', unread: '未読', artwork: '章のアート', artworkNote: 'しばらく絵を眺めてから、言葉に戻ろう。',
    aboutTitle: '良いコードは、ゆっくり読みたい。',
    aboutBody: '『The Art of Code』は、ソフトウェア設計を創造的な手仕事として捉える。物語やデータモデリングから、失敗の扱いと持続可能性まで、Sandrine Banas はコードの美しさを語り、実践する言葉を届ける。',
    aboutNotes: '提供された十章をもとに編集した独立の読書ノートです。概要、感想、要約文は編集上の解釈であり、書籍の内容と考えは原著者に帰属します。',
    ending: '読んだら、また創ろう。', top: '先頭に戻る', edition: '三言語の読本 / 十章のノート',
    forms: ['終わりのないひだ', '物語の流れ', 'ほどける複雑さ', '意図のかたち', '言葉の共鳴', '純粋な響き', '分かれて、再び', '成長の法則', '時間の堆積', '制約の中で咲く'],
    formNotes: ['細い線がねじれながら、一続きの曲面を織りなす。始まりも終わりもなく、同じ帯の上で秩序と変化が出会う。', '並行する物語の糸は途切れず、起伏を経て結末へ向かう。', '絡まった線が明快にほどけ、必要な複雑さに居場所を与える。', '境界と関係が読める立体をつくり、抽象的な意図に形を与える。', '二組の単純な円が出会い、一つでは生まれない表現になる。', '同心の波紋は一つの法則に従い、変化に隠れた驚きはない。', '線は空白を避けて分かれ、再び合流する。失敗の先にも道はある。', '種は一定の角度で並び、限られた空間に持続する秩序を見つける。', '輪郭が積み重なって地形となり、時間の中でも構造は読み取れる。', '制約された曲線が変奏を繰り返し、思いがけない花に育つ。'],
  },
};
